apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- ns.yaml
- vmks.yaml

configMapGenerator:
- name: vmks-values
  files:
  - values.yaml

configurations:
  - kustomizeconfig.yaml